Add end-of-life note to README.md
Giphy/giphy-python-client pull request #6
Opened 2023-01-24 01:57 UTC by timoludwig

As described in https://github.com/Giphy/giphy-python-client/issues/5#issuecomment-964291632 by @ethanlu, this client is not going to be supported anymore.

Since this package comes from the official @Giphy organization, it is given the impression that it works unless explicitly stated otherwise.

So I suggest to update the README and set the repository to "archived" to point out that users should look for alternatives.

Thanks a lot in advance for your feedback!

2023-01-24 15:07 UTC, khatkar requested changes
Thanks for proposing this change, it looks good. I'd request that you remove references to any third party alternatives. It is not fair for us to promote one lib over the others that exist.

2023-01-24 15:13 UTC, timoludwig commented
> I'd request that you remove references to any third party alternatives. It is not fair for us to promote one lib over the others that exist.

Alright, makes sense :+1:
I didn't find any other options, but I agree with the general concern.

2023-01-24 15:13 UTC, khatkar approved these changes

2023-02-03 11:29 UTC, timoludwig commented
@khatkar I don't have write permission to this repo, so I can't merge this PR, even though it's approved. So you'd have to merge it yourself if you want the changes to be present in the readme.

2023-02-03 15:16 UTC, merged